# Generated by Django 5.1.4 on 2025-01-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
